### ISSUE TITLE
Leaflet 1.9 ?

### ISSUE THREAD

**Issue by Mushr0000m** [w8r/Leaflet.Path.Transform#107]
Is it supposed to work with v1.9 ? I currently have an error `Uncaught Error: Invalid LatLng object: (NaN, NaN)` and seeing the releases names the v1.8.0 is still in beta to be compatible with Leaflet 1.8 ?

**Comment by w8r** [comment]
I will make an update for Leaflet 1.9. Out of curiosity, are there any critical 1.9 features that are motivating you to update?

**Comment by Mushr0000m** [comment]
Thank you ! No particular feature, but we always uses the latest stable version of packages when starting new projects.

**Comment by zilker** [comment]
Might save some time to someone - it happens if you create a map without the `maxZoom` option specified.
