### ISSUE TITLE
Rectangle not supported

### ISSUE THREAD

**Issue by axelerate** [w8r/Leaflet.Path.Transform#16]
Leaflet offers the Rectangle vector shape right out the box, but whenever I attempt to enable transformation and rotate it, the rectangle reverts back to an upright state.
Are there any plans to support rotation of rectangles?

**Comment by w8r** [comment]
That's strange, I will look into it

**Comment by w8r** [comment]
Fixed

**Comment by axelerate** [comment]
Thanks.
Do note that after this change has been introduced, the following errors pop up when dragging a rectangle, possible all paths:

Uncaught TypeError: L.DomEvent.fakeStop is not a function
L.Path.Transform-src.js:258 Uncaught TypeError: L.DomEvent.skipped is not a function

**Comment by w8r** [comment]
Please update leaflet to 1.1.0

**Comment by dt99jay** [comment]
I'm getting the same error at the end of dragging a rectangle with Leaflet 1.3.1:
```
L.Path.Transform.js:6
Uncaught TypeError: L.DomEvent.fakeStop is not a function
    at e._onDragEnd (L.Path.Transform.js:6)
    at HTMLDocument.h (leaflet-src.js:4200)
L.Path.Transform.js:6
Uncaught TypeError: L.DomEvent.skipped is not a function
    at e.<anonymous> (L.Path.Transform.js:6)
```
