### ISSUE TITLE
Error: Invalid LatLng object: (NaN, NaN)

### ISSUE THREAD

**Issue by zindelluib** [w8r/Leaflet.Path.Transform#18]
When I want to resize rectangles , they dont resize, and this message is appears:
Error: Invalid LatLng object: (NaN, NaN)
I use leaflet 0.7.3 and Leaflet.Path.Transform for Leaflet 0.7.3

**Comment by wethk** [comment]
thx, i had found the answer in https://github.com/w8r/Leaflet.Path.Transform/issues/4
