### ISSUE TITLE
how to adapt this to imageOverlay ?

### ISSUE THREAD

**Issue by elijahiuu** [w8r/Leaflet.Path.Transform#2]
Thanks for creating this plugin. Could you advise on how to adapt it to imageOverlay? It looks like all the calculations that are applied to <svg> 'transform' style would handle <image> as well as <path> elements.

**Comment by w8r** [comment]
@elijahiuu, well, they actually can be applied to css matrix as well. You might want to look at @OriginalSin's https://github.com/OriginalSin/Leaflet.DivTransform

**Comment by OriginalSin** [comment]
It is a pity that the video http://player.vimeo.com/video/92251790 was removed.
Sorry I don't have any other videos for example
