### ISSUE TITLE
Can I use images instead of polygons for this?

### ISSUE THREAD

**Issue by viswanathamsantosh** [w8r/Leaflet.Path.Transform#20]
Do you have any example for the same if it is already possible?

**Comment by w8r** [comment]
You can use the matrix from the control to apply it to the css transform for the image overlay. I don't have an example now, but maybe you can provide an image example for me to create a demo? I want it to be meaningful

**Comment by viswanathamsantosh** [comment]
I was trying to port this project< https://anyplace.cs.ucy.ac.cy/architect/ > from using google maps to osm using leaflet! I'm working on adding floorplans to the map but their isn't any stable plugin to add an image to osm map with rotate, drag, resize options. Your plugin has all that I need but i couldn't use images for now.

**Comment by viswanathamsantosh** [comment]
Hey @w8r , Do you find this request meaningful? Can you let me know how can i use an image instead of a polygon?

**Comment by w8r** [comment]
I find it meaningful, but it will definitely take quite some time to implement the example.
have you chance to take a look at this one?
https://github.com/OriginalSin/Leaflet.DivTransform
