### ISSUE TITLE
Leaflet.Path.Transform with Leaflet (not MapBox) "Cannot read property 'enable' of undefined" exception

### ISSUE THREAD

**Issue by astlin** [w8r/Leaflet.Path.Transform#21]
Can't make this plugin work with leaflet >= 1.0. Trying to enable() feature gives me "Uncaught TypeError: Cannot read property 'enable' of undefined" exception, while with MapBox works fine. See http://plnkr.co/edit/f3iyJKFhCRLo7FfDyOQI?p=preview

**Comment by w8r** [comment]
Wrong version, Leaflet@1.x - Leaflet.Path.Transform@1.x

http://plnkr.co/edit/fgbAkYTl9XpCRtPMGRfy?p=preview
