### ISSUE TITLE
setLatLngs on polygon after scaling does not update dashed resize box

### ISSUE THREAD

**Issue by gagecarto** [w8r/Leaflet.Path.Transform#26]
If I create a transformable polygon like 

`var printBoundary = L.polygon([...],{
      transform:true
    }).addTo(map)`

I can then drag its corners and the polygon resizes accordingly 

If I then change the polygons lat/lngs using setLatLngs 
`
printBoundary.setLatLngs([new lat lngs ])`

The polygon will resize accordingly but the dashed transform box does not update (see below). Could I setLatLngs on the resize box to account for this? 

![resize](https://user-images.githubusercontent.com/5776766/32959568-350094d4-cb7f-11e7-830c-987fcdb082b5.gif)

**Comment by w8r** [comment]
Well, I'm afraid the plugin has to be notified in order to take in the changes. I will take a look how to do it properly.

**Comment by jperelli** [comment]
For a similar issue I used
```
printBoundary.transform._updateHandlers()
```

**Comment by w8r** [comment]
I should make it public

**Comment by artuska** [comment]
Have the same issue. I have Leaflet.Editable and Leaflet.Transform both on my editable shape — when i drag shape vertex i want to refresh transform dashed box. How can i do this?

`_updateHandlers()` hack does not work.
