### ISSUE TITLE
Resetting the bounding box with transform.reset() seems to fail after the first time

### ISSUE THREAD

**Issue by dt99jay** [w8r/Leaflet.Path.Transform#34]
When changing a feature's geometry, `feature.transform.reset()` seems to correctly update the handles the first time, but not for subsequent geometry changes. Here's a minimal example: https://jsfiddle.net/xtv7c7sc/3/
I'm not sure if this is the same issue as #13.

**Comment by w8r** [comment]
Seems to be working

**Comment by m1900** [comment]
Unfortunately, I experience the same problem. However, when I change _getBoundingPolygon in Path.Transform.js to

`  _getBoundingPolygon: function() {
    return new L.Rectangle(
        this._path.getBounds(), this.options.boundsOptions);
  },
`

by leaving out the geometryToLayer call, the bounding box is sized correctly every time reset is called.

Version used: 1.1.2

**Comment by hammad2506** [comment]
If I'm using npm with this, and I don't want to directly modify the source file so others can easily get it working with npm install, how would you suggest me updating the above function? I believe it is not exposed on the transform enabled polyline. Thanks @m1900 

> Unfortunately, I experience the same problem. However, when I change _getBoundingPolygon in Path.Transform.js to
> 
> ` _getBoundingPolygon: function() { return new L.Rectangle( this._path.getBounds(), this.options.boundsOptions); },`
> 
> by leaving out the geometryToLayer call, the bounding box is sized correctly every time reset is called.
> 
> Version used: 1.1.2

**Comment by artuska** [comment]
+1. Issuing the same annoying problem.

@hammad2506 Look at my Leaflet overrides i use to avoid some problems and conflicts between Leaflet plugins:

leaflet.ts:

```import * as Leaflet from 'leaflet';

import 'leaflet';
import 'leaflet-draw';
import 'leaflet-editable';
import 'leaflet-path-transform';
import 'leaflet-semicircle';

import 'leaflet.arc';
import 'leaflet.draw-arc';
import 'leaflet.box';
import 'leaflet.draw-box';
import 'leaflet.sector';
import 'leaflet.draw-sector';

Leaflet.Circle.prototype.getCenter = Leaflet.Circle.prototype.getLatLng;

Leaflet.Handler['PathDrag'].prototype.updateLatLng = function() {};

Leaflet.Handler['PathTransform'].prototype._getBoundingPolygon = function() {
    return new Leaflet.Rectangle(this._path.getBounds(), this.options.boundsOptions);
};
```
