### ISSUE TITLE
Uncaught Error: Invalid LatLng object: (NaN, NaN)

### ISSUE THREAD

**Issue by axelerate** [w8r/Leaflet.Path.Transform#4]
Using the latest version of Leaflet and Leaflet.Path.Transform, zoom is always equals to infinity and matrix is made of NaN values. transformGeometries() does not pass in scale or angle data.
EDIT: This is caused if user does not specify maxzoom / min zoom.
If these values aren't manually set, I suggest assigning maxzoom to 18 and minzoom to 0.

**Comment by w8r** [comment]
Hi, I have somehow missed this issue. Yes, I should definitely create a limitation of `[0, 22]` or something similar
