### ISSUE TITLE
Control rotation outside leaflet map !

### ISSUE THREAD

**Issue by Kaplanwtf** [w8r/Leaflet.Path.Transform#42]
Hello,

i'm new on Github, and i want to know if we can rotate the polygon with control outside the leaflet map.

On mobile it will be easier.

**Comment by w8r** [comment]
Yes, here are the methods. Sorry they are not in the docs

https://github.com/w8r/Leaflet.Path.Transform/blob/master/src/Path.Transform.js#L199

**Comment by Kaplanwtf** [comment]
Can you show an example please ?

**Comment by w8r** [comment]
1. go to http://w8r.name/Leaflet.Path.Transform/example/
2. let's take the red polygon, for instance, it's available as the global `polygon`
3. let's rotate it by 30 degrees
```js
polygon.transform.rotate(Math.PI/180*30);
```

**Comment by Kaplanwtf** [comment]
Ok Thank you for your help.

But every time i got this erreor `polygon.transform.rotate is not a function`

polygon.tanform.enable work because i can rotate manually on the map my polygon.

**Comment by Kaplanwtf** [comment]
Hello i still have the same problem can someone help me ?

**Comment by w8r** [comment]
Please check if you have included all the right files of the latest version. You can see that it works on the example, and the `rotate` method is there
