### ISSUE TITLE
GeoJson

### ISSUE THREAD

**Issue by augustobg** [w8r/Leaflet.Path.Transform#5]
Does this is compatible with GeoJSON polygons?

**Comment by w8r** [comment]
MultiPolygons you mean?

**Comment by augustobg** [comment]
No, polygon but with a GEOJson format like:
{ "type": "Feature",
"properties": {
"name": name,
"popupContent": name,
},
         "geometry": {
           "type": "Polygon",
           "coordinates": [
             [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0],
               [100.0, 1.0], [100.0, 0.0] ]
             ]
         }

**Comment by w8r** [comment]
You mean a group of features? I don't understand the question. The plugin is a tool to transform features. GeoJSON like that one will result in a polygon, which you then can transform, yes
