### ISSUE TITLE
Example CSS references two SVG files that don't exist

### ISSUE THREAD

**Issue by teddyward** [w8r/Leaflet.Path.Transform#58]
https://github.com/w8r/Leaflet.Path.Transform/blob/e00c3b6a2c64b68fd0fd3aef5ed351488de1f3b3/example/css/topcoat-desktop-light.css#L2352

https://github.com/w8r/Leaflet.Path.Transform/blob/e00c3b6a2c64b68fd0fd3aef5ed351488de1f3b3/example/css/topcoat-desktop-light.css#L3308

What were these supposed to be?

**Comment by w8r** [comment]
Nah, I forgot them, but they don't matter in the demo

**Comment by teddyward** [comment]
Sorry, this other PR also needs to be merged (shouldn't have put the "closes" syntax in the first one, I know...)

https://github.com/w8r/Leaflet.Path.Transform/pull/64
