### ISSUE TITLE
Sample demo for using Leaflet.Path.Transform with Mapbox JS

### ISSUE THREAD

**Issue by rajkishan16** [w8r/Leaflet.Path.Transform#6]
Hey w8r,

I'm using Mapbox JS with Leaflet. I've been trying to find a way to rotate a polygon by dragging a corner or something similar, and I found that your Leaflet.Path.Transform does exactly what I need, like [this example](http://w8r.github.io/Leaflet.Path.Transform/example/) (mainly the rotating and dragging part). Thanks a lot for your work on this!!

I looked at your example, and tried to use that for my particular situation. But I haven't been able to figure out how to access the script file required for that. The GitHub page tells me to include the dist/L.Path.Transform.js file. So I went to [this page](https://github.com/w8r/Leaflet.Path.Transform/blob/master/dist/L.Path.Transform.js) and copied the code and pasted it in the script.js file in Plunker, and linked to it in the code. [This is](http://plnkr.co/edit/52jZIsZ2L9wtyuUsmbJl?p=preview) what I have so far in Plunker.

For now, I'm just trying to add a new polygon and try to rotate/drag that. But it is giving me some Javascript errors. Can you please point out to me what I'm doing wrong here? Or if there is some other simple demo that I can refer to, that'll be great as well.

Please let me know if you have any questions about my issue.

Thanks,
Rajkishan

**Comment by w8r** [comment]
What you probably need here is to include my other adapter - [Leaflet.Draw.Drag](https://github.com/w8r/leaflet.draw.drag)
But this will only add dragging,
as for rotation, I didn't make an integration with leaflet.draw yet. I will think about how I can do it

**Comment by w8r** [comment]
See, I added dragging here http://plnkr.co/edit/odoUrt6GcTFGcjlRl8oQ?p=preview

**Comment by rajkishan16** [comment]
Awesome!!! Thank you so much for your quick response.

This is exactly what I needed. I didn't know how to find this:
```
<script src='https://unpkg.com/leaflet-draw-drag@0.1.7/dist/Leaflet.draw.drag.js'></script>
<script src="https://unpkg.com/leaflet-path-transform@0.0.6/dist/L.Path.Transform.js"></script>
```
I tried to find this from the example, but I couldn't. But now thanks to you, I do.

Thanks again for your work!

Rajkishan
