### ISSUE TITLE
Is it possible to rotate programmatically?

### ISSUE THREAD

**Issue by AndrejSperling** [w8r/Leaflet.Path.Transform#7]
First, thank you for the library!
I would like to rotate a polygon without the transform handler. 

I'm trying to use the html range input.
At the moment i'm using the following code to rotate
```
var myAngle = 45;
polygon.transform.rotate(myAngle, null);
```
But it doesn't rotate in 45°, it rotate randomly, maybe i'm doing something wrong.
Is it possible? If yes, which methods to i have to use.

**Comment by w8r** [comment]
Angle is supposed to be in radians, not degrees
