### ISSUE TITLE
Rotate multiple polygons at once?

### ISSUE THREAD

**Issue by AndrejSperling** [w8r/Leaflet.Path.Transform#8]
Is it possible to rotate and move multiple polygons at once?

For example if i'm doing the following
```
<svg>

  <!-- First group of polygons -->
  <g>
     <path ... />
     <path ... />
  </g> 
 
  <!-- Second group of polygons -->
  <g>
     <path ... />
     <path ... />
  </g>

</svg>
```

Could i move or rotate the polygons inside a group (```<g>```) at once, for example the first group?

**Comment by w8r** [comment]
I'm afraid not, the tool works with paths individually, but you can combine them into a multipolygon, that will work. If you are concerned about the styling, create a copy, transform it and then copy the geometries back to your objects. It is only natural for edited objects to have single style
