### ISSUE TITLE
Still compatible with mapbox.js?

### ISSUE THREAD

**Issue by bram2000** [w8r/Leaflet.Path.Transform#81]
Is this library still compatible with `mapbox.js` running on the client side? When I try to source `https://cdn.jsdelivr.net/npm/leaflet-path-transform@1.1.3/index.min.js` directly from my html (as is done on the old examples, e.g. https://plnkr.co/edit/52jZIsZ2L9wtyuUsmbJl?p=preview&preview) I get console errors like:

```
index.js:1 Uncaught ReferenceError: require is not defined
    at index.js:1
```

This suggests it has to be used via node, but I don't think that used to be the case.

Thanks!

**Comment by w8r** [comment]
@bram2000 for adding directly in your HTML, please use the build version:
`https://cdn.jsdelivr.net/npm/leaflet-path-transform@1.1.3/dist/L.Path.Transform.js`
