### ISSUE TITLE
Applyting draggble for an already Existing layer

### ISSUE THREAD

**Issue by cubecleveland** [w8r/Leaflet.Path.Transform#86]
I was referring to issue #54  where they suggested to reinitiate the object in case the Polyline already existed.
We have a Geojson layer that already have the features drawn and we want to apply the transform on them...

the aboe method works, how can we apply the draggable method on them as well ?

**Comment by w8r** [comment]
I think it should work via `setOptions({ transform: true })`

**Comment by w8r** [comment]
More precisely
```ts
path.transform = new L.Handler.PathTransform(path, options);
path.transform.enable();
path.transform.disable();
```
